### ISSUE TITLE
Example with puppeteer

### ISSUE THREAD

**Issue by jlarmstrongiv** [hasankzl/htmlsvg#1]
Cool project!  I’d love to see an example with puppeteer—selecting an html element and then converting to svg.  

Also curious, how does htmlsvg deal with fonts?  Is it possible to replace all instances of a font with another fallback?

**Comment by hasankzl** [comment]
Hi jlarmstrongiv,
Here is a example with nodejs && puppeteer
`
// import script 
await page.addScriptTag({
      path: "htmlsvg.min.js",
    });
    await page.evaluate(async () => {
      const div = document.getElementsByClassName("site-title")[0];
      console.log(div);
      console.log(await htmlToSvg(div));
    });

`
htmlsvg basicly converts html elementsl like (div,p,h ..) to svg elements like (rect,text,image). for now its not working perfect and not support all css rules. It's good using  for basic problems but when it comes convert a website to svg it may not work great.

When htmlsvg try to convert a text first creates a svg text element and copies the current style of the text to the svg element.
Also copies the font-family.

**Comment by jlarmstrongiv** [comment]
Very cool!  Thank you 😄 do you have a list of elements or rules that don’t work—like psuedo elements, etc.?

**Comment by hasankzl** [comment]
"DIV":"ARTICLE":"MAIN"
"P": "H3": "H1": "H2":"H4":"H5":"SPAN":"A":"SMALL":"B":"BUTTON":
these are supported tags.
supported css rules:
color:
background-color
background-image
margin
padding
